### PR TITLE
Add results for Exynos 7880

### PR DESCRIPTION
**Pull request by Pokemetti**
For the results to be correct, turning off CPUs had to be disabled. Maybe I did some correction with the mif frequency too, but I don't fully remember.

### CODE REVIEW

**Comment by Pokemetti** [comment]
Maybe I will also upload results of an over-/underclocked version and of an undervolted version soon, but right now I've lent the phone to my dad. It will be interesting to see, whether undervolting actually does anything relevant.

**Comment by Pokemetti** [comment]
I forgot to add the phone (A5 2017) to the README in results, I should add that sometime

**Comment by Pokemetti** [comment]
I added the phone entry (Galaxy A5 2017) to the README.md and sorted the list according to the note at the top. I hope I didn't misunderstand the SoC marketing names.

**Review by kdrag0n — CHANGES_REQUESTED** [review]
Entries are sorted by internal names, not marketing names, so vendors are generally grouped together.

Also, can you mark your Exynos 7880 results as low accuracy? Any device that requires changes like disabling hotplugging will have lower-accuracy results, which is part of why I marked my Exynos 5250 results as low accuracy.

**Comment by kdrag0n** [comment]
Is this SoC supposed to have clusters? The results look quite odd: two frequency domains on CPUs 0 and 5, but identical frequencies and results on both.

**Comment by Pokemetti** [comment]
Thanks for clearing that up, I just followed the comment in the Readme file that clearly states that entries should be sorted "alphanumerically by SoC marketing name" and I set the accuracy to "Unknown" for the same reason. I couldn't know that you changed your mind and didn't update the only Documentation for this.

Yes, the SoC does have two clusters, though they contain the same CPUs configured exactly the same (as far as I can tell); both clusters have different clocksources and policies and with the stock Samsung hotplugging mechanism one cluster gets turned off unless there is a heavy load, which is a questionable mechanism but not the point of this comment I guess.
I mainly tested both clusters as a test whether the results match, which they didn't with normal freqbench, they were totally off (one cpu had the same drain at every frequency, the other had negative drain at times, etc.).

**Review by kdrag0n — APPROVED** [review]
Thanks for the updates and for fixing the documentation. I think that comment was from back when there were no SoCs from the same vendor that would be separated if sorted by marketing name, e.g. MediaTek Dimensity vs. Helio.

**Pull request merged**
